name: imp3.12
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy 
  - pandas
  - matplotlib
  - plotly
  - seaborn
  - jupyter
  - pybind11
  - pip:
    - kaleido
    - TSB-UAD